# Build
timeout: 60m0s
steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - --tag=us.gcr.io/deepsource-dev/swift-format:dev
      - .

images: ['us.gcr.io/deepsource-dev/swift-format:dev']

options:
  machineType: 'E2_HIGHCPU_8'
